<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>

		
		
  <title>Boost: throw_exception.hpp documentation</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>


	<body style="margin-left: 5%; margin-right: 5%;" bgcolor="white">

		
<table border="0" width="100%">

			<tbody>
    <tr>

				<td width="277"><a href="../../index.htm"> <img src="../../boost.png" alt="boost.png (6897 bytes)" border="0" height="86" width="277"></a>
				</td>

				<td align="center">
					
      <h1>throw_exception.hpp</h1>

				</td>

			</tr>

			<tr>

				<td colspan="2" height="64">&nbsp;</td>

			</tr>

		
  </tbody>
</table>

		
<p>头文件 <strong>&lt;boost/throw_exception.hpp&gt;</strong> 定义了辅助函数 <strong>boost::throw_exception</strong>. 它被用于需要抛出异常的 Boost 库，可以配置并支持不使用异常的平台，用 <strong>BOOST_NO_EXCEPTIONS</strong> <a href="../config/config.htm#macro_ref">
				配置宏</a> 来指明。
		</p>

		
<p>如果 <strong>BOOST_NO_EXCEPTIONS</strong> 没有被定义，则 <tt>boost::throw_exception(e)</tt>
			等同于 <tt>throw e</tt>. 否则，该函数为未定义，用户应该给出一个合适的定义。<tt>throw_exception</tt>
			的调用者被允许假定该函数不会返回；因此，如果用户定义的 <tt>throw_exception</tt> 会返回，则行为也是未定义的。</p>

		
<h3><a name="Synopsis">概要</a></h3>

		
<pre>namespace boost<br>{<br><br>#ifdef BOOST_NO_EXCEPTIONS<br><br>void throw_exception(std::exception const &amp; e); // 用户定义<br><br>#else<br><br>template&lt;class E&gt; void throw_exception(E const &amp; e)<br>{<br>    throw e;<br>}<br><br>#endif<br><br>}<br></pre>

		
<p><br>

			<small>Copyright &copy; 2002 by Peter Dimov. Distributed under the Boost Software License, Version 
				1.0. See accompanying file <a href="../../LICENSE_1_0.txt">LICENSE_1_0.txt</a> or 
				copy at <a href="http://www.boost.org/LICENSE_1_0.txt">http://www.boost.org/LICENSE_1_0.txt</a>.</small></p>

	
</body>
</html>
